apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collatz-app
  template:
    metadata:
      labels:
        app: collatz-app
    spec:
      containers:
        - name: collatz-app
          image: collatz_app:latest
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: collatz-app-service
  labels:
    app: collatz-app
spec:
  type: NodePort
  selector:
    app: collatz-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080